# Generated by Django 2.2 on 2022-04-02 10:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_auto_20220401_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='rights_num',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(1023), django.core.validators.MinValueValidator(0)]),
        ),
    ]
