# Generated by Django 2.2 on 2022-04-02 11:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_auto_20220402_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='rights_num',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1023), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='rights_num',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1023), django.core.validators.MinValueValidator(0)]),
        ),
    ]
