# Generated by Django 2.2 on 2022-04-02 12:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_auto_20220402_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='rights_num',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(1023), django.core.validators.MinValueValidator(0)]),
        ),
    ]
